name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Prepare
      run: |
        New-Item -Path "Publish" -ItemType Directory
        Copy-Item -Path "D:\a\WannaCriCS\WannaCriCS\Assets\FFmpeg" -Destination "Publish" -Recurse -Force
        Copy-Item -Path "D:\a\WannaCriCS\WannaCriCS\Assets\Python" -Destination "Publish" -Recurse -Force
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
  
    - name: Add CosturaFody
      run: dotnet add package Costura.Fody      
      
    - name: Build
      run: msbuild D:\a\WannaCriCS\WannaCriCS\WannaCriCS.sln -property:Configuration=Release

    - name: Copy Files
      run: Copy-Item -Path "D:\a\WannaCriCS\WannaCriCS\bin\Release\app.publish\WannaCriCS.exe" -Destination "Publish" -Force
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Publish
        path: Publish
      
